#!/usr/bin/env sh

# env "PATH=$PATH" allows to resolve 'which node' in sudo mode
sudo env "PATH=$PATH" ./node_modules/.bin/add-to-systemd \
   --env FORCE_COLOR=true \
   os-health-report "$(which node) $(pwd)/index.js"
