#!/usr/bin/env sh

echo "Starting to create self-signed keys, you may let all the following fields blank"
mkdir -p ./keys
cd ./keys
# Create self-signed keys to use TLS
openssl req -x509 -sha256 -nodes -days 1095 -newkey rsa:2048 -keyout self-signed.key -out self-signed.crt -subj "/C=/ST=/L=/O=/OU=/CN=."

echo "Done with creating self-signed keys"
